### ISSUE TITLE
Missing support for external .tsx tilesets

### ISSUE THREAD

**Issue by vnen** [vnen/godot-tiled-importer#5]

**Comment by SleepProgger** [comment]
As far as i see external .tsx support is still missing for json maps.
Its not that bad IMHO but it should be fixed or at least written down somewhere in the Readme i guess.

**Comment by vnen** [comment]
Oh, I haven't looked at how `.json` maps handle this. Reopening this until it's fixed,

**Comment by tamkcr** [comment]
Somewhat related, `var rel_id = str(gid - firstgid)` (line 164 assetlib version of tiled_import.gd) seem to cause skips for objects in .tsx tilsets on my end. 

I think this is because _attributes_to_dict() used is_valid_integer() to parse the tsx xml to json so the tile ids are actually int causing `rel_id in ts.tiles` (line 166) to give false.

Making `var rel_id = gid - firstgid` worked but I assume this will break straight json maps. Perhaps do a typeof() check on one sample of `ts.tiles` to determine if a string conversion is needed?

**Comment by vnen** [comment]
@tamkcr this problem was fixed in master, not yet in the AssetLib though.

**Comment by vnen** [comment]
Fixed support for external maps. Now `.tmx` maps supports `.json` tilesets too (e3c66ed) and `.json` maps also supports both formats (5db9e9f).
